### ISSUE TITLE
Erro no tamanho dos campos R60R.

### ISSUE THREAD

**Issue by gustavoamorimqueiroz** [samuelrochaoliveira/SINTEGRABr#5]
Olá. 

Sobre a quantidade de casas decimais do campo receita bruta e totalizador geral (R60R), o correto não seria tamanho 16 com 2 casas decimais? Na ultima versão o tamanho está 14. Rodei aqui e deu certo nas linhas do registro R60R.

Att,

**Comment by samuelroliveira** [comment]
Olá @gustavoamorimqueiroz, correção feita no commit https://github.com/samuelroliveira/SINTEGRABr/commit/9a59c725f586c22a8dd4f6032fa9cf3354f79371.
